# Generated by Django 4.0.6 on 2022-08-09 21:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('correct_answer', models.CharField(max_length=100)),
                ('incorrect_answer', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=None)),
            ],
        ),
    ]
